spring :
  mail :
    host : smtp.gmail.com
    port : 587
    username : 'minseongyu26@gmail.com'
    password : 'nqyjejaijktzzrck'
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: als5066303!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        default_batch_fetch_size: 100
        format_sql: true
  profiles:
    active:
      - local
logging.level:
  org.hibernate.SQL: debug